name: 'tofu deployment'
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
jobs:
  tf_fmt:
    name: 'tofu fmt'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: "./"

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup tofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.9.1

      - name: tofu Fmt
        id: FMT
        run: tofu fmt --recursive

  tf_plan_apply:
    needs: [ "tf_fmt" ]
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    uses: ./.github/workflows/tf_template.yaml
    with:
      dir_name: ./
      tf_key: bootstrap
    secrets:
      service_account: '${{ secrets.SERVICE_ACCOUNT }}'
      WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}