name: 'Run tofu'
on:
  workflow_call:
    inputs:
      dir_name:
        description: 'Specifies the path of the root tofu module.'
        required: true
        type: string
      tf_key:
        description: 'Specifies the tofu state file name for this plan. Workflow artifact will use same name'
        required: true
        type: string
    secrets:
      WORKLOAD_IDENTITY_PROVIDER:
        required: true
      SERVICE_ACCOUNT:
        required: true
jobs:
  tf_plan_pr:
    name: 'TF plan'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    if: ${{ github.event_name == 'pull_request' }}
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.dir_name }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup tofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.9.1

      - name: Configure GCP credentials
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'
          create_credentials_file: true
          service_account: '${{ secrets.SERVICE_ACCOUNT }}'    
          token_format: "access_token"
          access_token_lifetime: "120s"

      - name: tofu Init
        id: init
        run: tofu init -input=false
      
      - name: tofu Validate
        id: validate
        run: tofu validate -no-color
      
      - name: tofu Plan
        id: plan
        run: tofu plan -no-color -input=false
        continue-on-error: true

      - uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        env:
          PLAN: "tofu\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // 1. Retrieve existing bot comments for the PR
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            })
            const botComment = comments.find(comment => {
              return comment.user.type === 'Bot' && comment.body.includes('OpenTofu Format and Style')
            })
      
            // 2. Prepare format of the comment
            const output = `#### OpenTofu Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### OpenTofu Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### OpenTofu Validation 🤖\`${{ steps.validate.outcome }}\`
            <details><summary>Validation Output</summary>
      
            \`\`\`\n
            ${{ steps.validate.outputs.stdout }}
            \`\`\`
      
            </details>
      
            #### OpenTofu Plan 📖\`${{ steps.plan.outcome }}\`
      
            <details><summary>Show Plan</summary>
      
            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`
      
            </details>
      
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;
      
            // 3. If we have a comment, update it, otherwise create a new one
            if (botComment) {
              github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: output
              })
            } else {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: output
              })
            }
                
  tf_apply:
    name: 'Init, Plan and apply'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main'}}
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.dir_name }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup tofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.9.1

      - name: Configure GCP credentials
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'
          create_credentials_file: true
          service_account: '${{ secrets.SERVICE_ACCOUNT }}'    
          token_format: "access_token"
          access_token_lifetime: "120s"

      - name: tofu Init
        id: init
        run: tofu init -input=false

      - name: Plan tofu
        id: plan
        continue-on-error: true
        run: |
          tofu plan -input=false -no-color -out=tfplan \
          && tofu show -no-color tfplan

      - name: Apply tofu
        if: steps.plan.outcome == 'success'
        id: apply
        continue-on-error: true
        run: |
          tofu apply \
            -input=false \
            -no-color \
            "tfplan"